version: '3.1'
services:
  quotes-service:
    build:
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - partner
    environment:
      REDIS_HOST: redis
      PARTNERS_HOST: partner

  partner:
    build: './partner'

  redis:
    image: redis:alpine
